language: scala
scala:
- 2.11.8
jdk:
- oraclejdk8
services:
  - postgresql
before_script:
  - psql -c 'create database urlchecker;' -U postgres
  - psql -U postgres -d urlchecker ./sql/schema.create.sql
script:
  - sbt test
