language: scala
scala:
- 2.11.8
jdk:
- oraclejdk8
services:
  - postgresql
before_script:
  - psql -U postgres -c 'create database urlchecker;'
  - psql -U postgres -d urlchecker -f ./sql/schema.create.sql
script:
  - sbt test
